apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    version: 1.4.5
    team: finance
    key: mylabel
  annotation:
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80