apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    version: 1.0.3
    team: product
    environtment: development
  annotations:
    descripttion: This is product description
    anything: bla bla bla 
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80